In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("netflix_data.csv")

In [4]:
df.head(n=18)

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas
5,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,1,A genetics professor experiments with a treatm...,International TV
6,s7,Movie,122,Yasir Al Yasiri,"Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...",Egypt,"June 1, 2020",2019,95,"After an awful accident, a couple admitted to ...",Horror Movies
7,s8,Movie,187,Kevin Reynolds,"Samuel L. Jackson, John Heard, Kelly Rowan, Cl...",United States,"November 1, 2019",1997,119,After one of his high school students attacks ...,Dramas
8,s9,Movie,706,Shravan Kumar,"Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...",India,"April 1, 2019",2019,118,"When a doctor goes missing, his psychiatrist w...",Horror Movies
9,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,"December 15, 2017",2008,143,An architect and his wife move into a castle t...,Horror Movies
10,s11,Movie,1922,Zak Hilditch,"Thomas Jane, Molly Parker, Dylan Schmid, Kaitl...",United States,"October 20, 2017",2017,103,A farmer pens a confession admitting to his wi...,Dramas
11,s12,TV Show,1983,NaN,"Robert Więckiewicz, Maciej Musiał, Michalina O...",Poland,"November 30, 2018",2018,1,"In this dark alt-history thriller, a naïve law...",Crime TV
12,s13,TV Show,1994,Diego Enrique Osorno,NaN,Mexico,"May 17, 2019",2019,1,Archival video and new interviews examine Mexi...,Crime TV
13,s14,Movie,"2,215",Nottapon Boonprakob,Artiwara Kongmalai,Thailand,"March 1, 2019",2018,89,This intimate documentary follows rock star Ar...,Documentaries
14,s15,Movie,3022,John Suits,"Omar Epps, Kate Walsh, Miranda Cosgrove, Angus...",United States,"March 19, 2020",2019,91,Stranded when the Earth is suddenly destroyed ...,Independent Movies
15,s16,Movie,Oct-01,Kunle Afolayan,"Sadiq Daba, David Bailie, Kayode Olaiya, Kehin...",Nigeria,"September 1, 2019",2014,149,Against the backdrop of Nigeria's looming inde...,Dramas
16,s17,TV Show,Feb-09,NaN,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",NaN,"March 20, 2019",2018,1,"As a psychology professor faces Alzheimer's, h...",International TV
17,s18,Movie,22-Jul,Paul Greengrass,"Anders Danielsen Lie, Jon Øigarden, Jonas Stra...",Norway,"October 10, 2018",2018,144,"After devastating terror attacks in Norway, a ...",Dramas

# Question 1

## Add col "num_of_cast" in the dataset which contains the total number of cast in that particular movie or Tv-Show.

In [5]:
# check if there is any null value in col "cast"
df["cast"].isnull().sum()

718

In [6]:
# replace null value wit "None"

df["cast"] = df['cast'].replace(np.nan, "None")

In [7]:
# total num of cast using this function

def get_no_of_cast(value):
    if value != "None":
        return len(value.split(", "))
    
    return 0

In [8]:
# add col "num_of_cast" in the dataset

df["num_of_cast"] = df["cast"].apply(get_no_of_cast)

In [9]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre,num_of_cast
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,4,In a future where the elite inhabit an island ...,International TV,11
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,93,After a devastating earthquake hits Mexico Cit...,Dramas,6
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,78,"When an army recruit is found dead, his fellow...",Horror Movies,9
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action,9
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,123,A brilliant group of students become card-coun...,Dramas,12

# Question 2

## Count how many number of tv-shows and movies of each genre

In [36]:
# first group the data according to type(tv-shows and movies)

df1 = df.groupby("type")

In [37]:
# get count of tv-shows and movies of each genre

df1["genre"].value_counts()

type     genre
Movie    Dramas                  1384
         Comedies                1074
         Documentaries            751
         Action                   721
         Children                 502
         Stand-Up                 321
         Horror Movies            244
         International Movies     114
         Classic Movies            77
         Uncategorized             56
         Thrillers                 49
         Independent Movies        20
         Anime Features            19
         Music                     17
         Cult Movies               12
         Sci-Fi                    11
         Romantic Movies            3
         LGBTQ Movies               1
         Sports Movies              1
TV Show  International TV         690
         Crime TV                 369
         Kids                     359
         British TV               232
         Docuseries               194
         Anime Series             148
         TV Comedies              110
         Reality TV               102
         TV Dramas                 62
         TV Action                 37
         Stand-Up                  33
         Romantic TV               28
         Classic                   21
         TV Shows                  12
         TV Horror                 10
         Spanish-Language           2
         TV Sci                     1
Name: genre, dtype: int64